export const tourSteps = [
  {
    id: 'balance-carousel',
    page: '/home',
    selector: '.home-balance-carousel',
    title: 'Tu resumen financiero',
    description: 'Balance, ingresos y egresos. Desliza para ver cada tarjeta.',
    position: 'bottom',
  },
  {
    id: 'search-period',
    page: '/home',
    selector: '.home-search-period-row',
    title: 'Busca y filtra',
    description: 'Busca por placa, nombre. Usa filtros avanzados.',
    position: 'bottom',
  },
  {
    id: 'tab-pills',
    page: '/home',
    selector: '.home-tab-pills',
    title: 'Servicios, Productos y Movimientos',
    description: 'Cambia entre pestañas de servicios, ventas y movimientos.',
    position: 'bottom',
  },
  {
    id: 'fab',
    page: '/home',
    selector: '.home-fab',
    title: 'Botón de acción rápida',
    description: 'Registrar servicio, cliente, venta o ingreso/egreso.',
    position: 'top',
  },
  {
    id: 'nav-dashboard',
    page: '/home',
    selector: '.sidebar-nav a[href="/dashboard"], .floating-bottom-bar a[href="/dashboard"]',
    title: 'Análisis',
    description: 'Gráficas de ventas, servicios por tipo, rendimiento.',
    position: 'top',
  },
  {
    id: 'analisis-filters',
    page: '/dashboard',
    selector: '.analisis-filters',
    title: 'Reportes y análisis',
    description: 'Filtra por fechas y periodo para analizar rendimiento.',
    position: 'bottom',
  },
  {
    id: 'nav-clientes',
    page: '/dashboard',
    selector: '.sidebar-nav a[href="/clientes"], .floating-bottom-bar a[href="/clientes"]',
    title: 'Clientes',
    description: 'Administra clientes, membresías e historial.',
    position: 'top',
  },
  {
    id: 'clientes-search',
    page: '/clientes',
    selector: '.clientes-search-row',
    title: 'Busca tus clientes',
    description: 'Busca por nombre, placa o cédula. Filtra por membresía.',
    position: 'bottom',
  },
  {
    id: 'nav-trabajadores',
    page: '/clientes',
    selector: '.sidebar-nav a[href="/pagos"], .floating-bottom-bar a[href="/pagos"]',
    title: 'Trabajadores',
    description: 'Registra pagos, calcula comisiones y controla el rendimiento de tu equipo.',
    position: 'top',
  },
  {
    id: 'nav-cuenta',
    page: '/clientes',
    selector: '.sidebar-nav a[href="/cuenta"], .floating-bottom-bar a[href="/cuenta"]',
    title: 'Cuenta',
    description: 'Tu perfil, plan, configuración y soporte.',
    position: 'top',
  },
  {
    id: 'cuenta-config',
    page: '/cuenta',
    selector: '.cuenta-tab-config',
    title: 'Configuración',
    description: 'Configura tipos de servicio, membresías, métodos de pago y más.',
    position: 'bottom',
  },
  {
    id: 'cuenta-soporte',
    page: '/cuenta',
    selector: '.cuenta-tab-soporte',
    title: 'Soporte',
    description: 'Escríbenos por WhatsApp o correo si necesitas ayuda.',
    position: 'bottom',
  },
]
